(function () {
const dictionaries = {
  en: { companion:"Browser Companion",checking:"Checking",connected:"Connected",offline:"Offline",appOffline:"Mac app isn’t running",appOfflineHint:"Open it in the background to enable downloads and sync.",openApp:"Open App",settings:"Settings",appearance:"Appearance",about:"About",extension:"EXTENSION",detection:"Browser detection",detectionHint:"Recognize supported video and image cards as you browse.",quickControls:"Quick controls",floatingButton:"Floating download button",floatingHint:"Only appears near visible media",quality:"Default quality",qualityHint:"Used when you press quick download",scanRegion:"Detection region",scanRegionHint:"Focus on the middle or use the full screen",middle:"Middle",full:"Full screen",syncNote:"Changes sync with the Mac app when connected.",language:"Language",interfaceLanguage:"Interface language",languageHint:"Popup and media controls",theme:"Glass theme",themeHint:"Synced with the Mac app",system:"System",darkGlass:"Dark",lightGlass:"Light",localFirst:"Local-first connection",localFirstHint:"Settings and download requests stay on your Mac.",fast:"Fast companion",fastHint:"Lightweight detection near visible media only.",twoWay:"Two-way sync",twoWayHint:"Change settings here or in the menu bar app.",saved:"Settings saved",localOnly:"Secure local connection",thisWebsite:"This website",optIn:"OPT-IN",siteHint:"Detect large media only on this domain" },
  vi: { companion:"Tiện ích trình duyệt",checking:"Đang kiểm tra",connected:"Đã kết nối",offline:"Chưa kết nối",appOffline:"App Mac chưa chạy",appOfflineHint:"Mở app chạy nền để tải và đồng bộ cài đặt.",openApp:"Mở App",settings:"Cài đặt",appearance:"Giao diện",about:"Giới thiệu",extension:"TIỆN ÍCH",detection:"Nhận diện trên trình duyệt",detectionHint:"Nhận diện thẻ video và ảnh được hỗ trợ khi bạn duyệt.",quickControls:"Điều khiển nhanh",floatingButton:"Nút tải nổi",floatingHint:"Chỉ hiện gần nội dung trên màn hình",quality:"Chất lượng mặc định",qualityHint:"Dùng khi bấm nút tải nhanh",scanRegion:"Vùng nhận diện",scanRegionHint:"Tập trung ở giữa hoặc dùng toàn màn hình",middle:"Giữa màn hình",full:"Toàn màn hình",syncNote:"Thay đổi sẽ đồng bộ với app Mac khi kết nối.",language:"Ngôn ngữ",interfaceLanguage:"Ngôn ngữ giao diện",languageHint:"Popup và nút điều khiển nội dung",theme:"Giao diện kính",themeHint:"Đồng bộ với app Mac",system:"Hệ thống",darkGlass:"Tối",lightGlass:"Sáng",localFirst:"Kết nối nội bộ",localFirstHint:"Cài đặt và yêu cầu tải chỉ nằm trên máy Mac.",fast:"Tiện ích nhẹ",fastHint:"Chỉ nhận diện nội dung đang hiện gần màn hình.",twoWay:"Đồng bộ hai chiều",twoWayHint:"Thay đổi tại đây hoặc trong app menu bar.",saved:"Đã lưu cài đặt",localOnly:"Kết nối nội bộ an toàn",thisWebsite:"Website hiện tại",optIn:"TỰ CHỌN",siteHint:"Chỉ nhận diện media lớn trên tên miền này" },
  zh: { companion:"浏览器助手",checking:"检查中",connected:"已连接",offline:"未连接",appOffline:"Mac 应用未运行",appOfflineHint:"在后台打开应用以启用下载和同步。",openApp:"打开应用",settings:"设置",appearance:"外观",about:"关于",extension:"扩展程序",detection:"浏览器检测",detectionHint:"浏览时识别支持的视频和图片。",quickControls:"快速控制",floatingButton:"悬浮下载按钮",floatingHint:"仅在可见媒体附近显示",quality:"默认画质",qualityHint:"用于快速下载按钮",scanRegion:"检测区域",scanRegionHint:"聚焦屏幕中部或使用全屏",middle:"屏幕中部",full:"全屏",syncNote:"连接后更改会与 Mac 应用同步。",language:"语言",interfaceLanguage:"界面语言",languageHint:"弹窗和媒体控件",theme:"玻璃主题",themeHint:"与 Mac 应用同步",system:"系统",darkGlass:"深色",lightGlass:"浅色",localFirst:"本地连接",localFirstHint:"设置和下载请求保留在 Mac 上。",fast:"轻量助手",fastHint:"仅检测屏幕附近的媒体。",twoWay:"双向同步",twoWayHint:"可在此处或菜单栏应用中更改设置。",saved:"设置已保存",localOnly:"安全本地连接",thisWebsite:"当前网站",optIn:"可选",siteHint:"仅在此域名检测大型媒体" },
};
const supported = ["en","vi","zh","es","fr","de","pt","ja","ko"];


  // Additional languages below use the same key contract as English.
  const additional = {
    es: { companion:"Complemento del navegador",checking:"Comprobando",connected:"Conectado",offline:"Sin conexión",appOffline:"La app de Mac no está abierta",appOfflineHint:"Ábrela en segundo plano para descargar y sincronizar.",openApp:"Abrir app",settings:"Ajustes",appearance:"Apariencia",about:"Acerca de",extension:"EXTENSIÓN",detection:"Detección del navegador",detectionHint:"Reconoce vídeos e imágenes compatibles mientras navegas.",quickControls:"Controles rápidos",floatingButton:"Botón flotante de descarga",floatingHint:"Solo aparece junto a contenido visible",quality:"Calidad predeterminada",qualityHint:"Se usa al pulsar la descarga rápida",scanRegion:"Zona de detección",scanRegionHint:"El centro o toda la pantalla",middle:"Centro",full:"Toda la pantalla",syncNote:"Los cambios se sincronizan con la app de Mac al conectar.",language:"Idioma",interfaceLanguage:"Idioma de la interfaz",languageHint:"Ventana y controles multimedia",theme:"Tema de cristal",themeHint:"Sincronizado con la app de Mac",system:"Sistema",darkGlass:"Oscuro",lightGlass:"Claro",localFirst:"Conexión local",localFirstHint:"Los ajustes y las solicitudes permanecen en tu Mac.",fast:"Complemento ligero",fastHint:"Solo detecta contenido visible cercano.",twoWay:"Sincronización bidireccional",twoWayHint:"Cambia ajustes aquí o en la app de la barra de menús.",saved:"Ajustes guardados",localOnly:"Conexión local segura",thisWebsite:"Este sitio web",optIn:"OPCIONAL",siteHint:"Detectar contenido grande solo en este dominio",best:"Mejor",auto:"Automático",localSync:"Sincronización local",version:"Versión",sections:"Secciones de la extensión",website:"Sitio web" },
    fr: { companion:"Extension du navigateur",checking:"Vérification",connected:"Connecté",offline:"Hors ligne",appOffline:"L’app Mac n’est pas ouverte",appOfflineHint:"Ouvrez-la en arrière-plan pour télécharger et synchroniser.",openApp:"Ouvrir l’app",settings:"Réglages",appearance:"Apparence",about:"À propos",extension:"EXTENSION",detection:"Détection du navigateur",detectionHint:"Repère les vidéos et images compatibles pendant la navigation.",quickControls:"Commandes rapides",floatingButton:"Bouton flottant de téléchargement",floatingHint:"Affiché près du contenu visible uniquement",quality:"Qualité par défaut",qualityHint:"Utilisée pour le téléchargement rapide",scanRegion:"Zone de détection",scanRegionHint:"Le centre ou tout l’écran",middle:"Centre",full:"Tout l’écran",syncNote:"Les modifications se synchronisent avec l’app Mac à la connexion.",language:"Langue",interfaceLanguage:"Langue de l’interface",languageHint:"Fenêtre et commandes multimédias",theme:"Thème de verre",themeHint:"Synchronisé avec l’app Mac",system:"Système",darkGlass:"Sombre",lightGlass:"Clair",localFirst:"Connexion locale",localFirstHint:"Réglages et demandes restent sur votre Mac.",fast:"Extension légère",fastHint:"Détecte uniquement le contenu visible à proximité.",twoWay:"Synchronisation bidirectionnelle",twoWayHint:"Modifiez les réglages ici ou dans l’app de la barre des menus.",saved:"Réglages enregistrés",localOnly:"Connexion locale sécurisée",thisWebsite:"Ce site web",optIn:"FACULTATIF",siteHint:"Détecter le contenu volumineux sur ce domaine uniquement",best:"Meilleure",auto:"Automatique",localSync:"Synchronisation locale",version:"Version",sections:"Sections de l’extension",website:"Site web" },
    de: { companion:"Browser-Erweiterung",checking:"Prüfung läuft",connected:"Verbunden",offline:"Nicht verbunden",appOffline:"Die Mac-App ist nicht geöffnet",appOfflineHint:"Im Hintergrund öffnen, um Downloads und Synchronisierung zu aktivieren.",openApp:"App öffnen",settings:"Einstellungen",appearance:"Darstellung",about:"Über",extension:"ERWEITERUNG",detection:"Browser-Erkennung",detectionHint:"Erkennt unterstützte Videos und Bilder beim Surfen.",quickControls:"Schnellsteuerung",floatingButton:"Schwebende Download-Taste",floatingHint:"Nur bei sichtbaren Medien angezeigt",quality:"Standardqualität",qualityHint:"Für den schnellen Download",scanRegion:"Erkennungsbereich",scanRegionHint:"Mitte oder gesamter Bildschirm",middle:"Mitte",full:"Ganzer Bildschirm",syncNote:"Änderungen werden bei Verbindung mit der Mac-App synchronisiert.",language:"Sprache",interfaceLanguage:"Oberflächensprache",languageHint:"Popup und Mediensteuerung",theme:"Glasdesign",themeHint:"Mit der Mac-App synchronisiert",system:"System",darkGlass:"Dunkel",lightGlass:"Hell",localFirst:"Lokale Verbindung",localFirstHint:"Einstellungen und Anfragen bleiben auf deinem Mac.",fast:"Leichte Erweiterung",fastHint:"Erkennt nur sichtbare Medien in der Nähe.",twoWay:"Zweiseitige Synchronisierung",twoWayHint:"Hier oder in der Menüleisten-App ändern.",saved:"Einstellungen gespeichert",localOnly:"Sichere lokale Verbindung",thisWebsite:"Diese Website",optIn:"OPTIONAL",siteHint:"Große Medien nur auf dieser Domain erkennen",best:"Beste",auto:"Automatisch",localSync:"Lokale Synchronisierung",version:"Version",sections:"Bereiche der Erweiterung",website:"Website" },
    pt: { companion:"Extensão do navegador",checking:"Verificando",connected:"Conectado",offline:"Desconectado",appOffline:"O app do Mac não está aberto",appOfflineHint:"Abra em segundo plano para baixar e sincronizar.",openApp:"Abrir app",settings:"Ajustes",appearance:"Aparência",about:"Sobre",extension:"EXTENSÃO",detection:"Detecção no navegador",detectionHint:"Reconhece vídeos e imagens compatíveis enquanto você navega.",quickControls:"Controles rápidos",floatingButton:"Botão flutuante de download",floatingHint:"Aparece apenas perto de conteúdo visível",quality:"Qualidade padrão",qualityHint:"Usada no download rápido",scanRegion:"Área de detecção",scanRegionHint:"Centro ou tela inteira",middle:"Centro",full:"Tela inteira",syncNote:"As alterações são sincronizadas com o app do Mac ao conectar.",language:"Idioma",interfaceLanguage:"Idioma da interface",languageHint:"Janela e controles de mídia",theme:"Tema de vidro",themeHint:"Sincronizado com o app do Mac",system:"Sistema",darkGlass:"Escuro",lightGlass:"Claro",localFirst:"Conexão local",localFirstHint:"Ajustes e solicitações permanecem no seu Mac.",fast:"Extensão leve",fastHint:"Detecta apenas conteúdo visível próximo.",twoWay:"Sincronização bidirecional",twoWayHint:"Altere aqui ou no app da barra de menus.",saved:"Ajustes salvos",localOnly:"Conexão local segura",thisWebsite:"Este site",optIn:"OPCIONAL",siteHint:"Detectar mídia grande apenas neste domínio",best:"Melhor",auto:"Automático",localSync:"Sincronização local",version:"Versão",sections:"Seções da extensão",website:"Site" },
    ja: { companion:"ブラウザー拡張機能",checking:"確認中",connected:"接続済み",offline:"未接続",appOffline:"Macアプリが起動していません",appOfflineHint:"バックグラウンドで開くとダウンロードと同期が使えます。",openApp:"アプリを開く",settings:"設定",appearance:"外観",about:"このアプリについて",extension:"拡張機能",detection:"ブラウザーでの検出",detectionHint:"閲覧中に対応する動画や画像を検出します。",quickControls:"クイック設定",floatingButton:"フローティングダウンロードボタン",floatingHint:"表示中のメディア付近にのみ表示",quality:"標準画質",qualityHint:"クイックダウンロード時に使用",scanRegion:"検出範囲",scanRegionHint:"画面中央または画面全体",middle:"中央",full:"画面全体",syncNote:"接続時に変更内容がMacアプリと同期されます。",language:"言語",interfaceLanguage:"表示言語",languageHint:"ポップアップとメディア操作",theme:"ガラステーマ",themeHint:"Macアプリと同期",system:"システム",darkGlass:"ダーク",lightGlass:"ライト",localFirst:"ローカル接続",localFirstHint:"設定とダウンロード要求はMac内に留まります。",fast:"軽量な拡張機能",fastHint:"表示中の近くのメディアだけを検出します。",twoWay:"双方向同期",twoWayHint:"ここでもメニューバーアプリでも設定を変更できます。",saved:"設定を保存しました",localOnly:"安全なローカル接続",thisWebsite:"このサイト",optIn:"任意",siteHint:"このドメイン内の大きなメディアのみ検出",best:"最高",auto:"自動",localSync:"ローカル同期",version:"バージョン",sections:"拡張機能のセクション",website:"ウェブサイト" },
    ko: { companion:"브라우저 확장 프로그램",checking:"확인 중",connected:"연결됨",offline:"연결 안 됨",appOffline:"Mac 앱이 실행되지 않았습니다",appOfflineHint:"백그라운드에서 열어 다운로드와 동기화를 사용하세요.",openApp:"앱 열기",settings:"설정",appearance:"외관",about:"정보",extension:"확장 프로그램",detection:"브라우저 감지",detectionHint:"탐색 중 지원되는 동영상과 이미지를 감지합니다.",quickControls:"빠른 설정",floatingButton:"플로팅 다운로드 버튼",floatingHint:"화면에 보이는 미디어 근처에만 표시",quality:"기본 화질",qualityHint:"빠른 다운로드에 사용",scanRegion:"감지 영역",scanRegionHint:"화면 중앙 또는 전체 화면",middle:"중앙",full:"전체 화면",syncNote:"연결되면 변경 사항이 Mac 앱과 동기화됩니다.",language:"언어",interfaceLanguage:"인터페이스 언어",languageHint:"팝업 및 미디어 컨트롤",theme:"글래스 테마",themeHint:"Mac 앱과 동기화",system:"시스템",darkGlass:"어둡게",lightGlass:"밝게",localFirst:"로컬 연결",localFirstHint:"설정과 다운로드 요청은 Mac에만 저장됩니다.",fast:"가벼운 확장 프로그램",fastHint:"근처에 표시된 미디어만 감지합니다.",twoWay:"양방향 동기화",twoWayHint:"여기 또는 메뉴 막대 앱에서 설정을 변경하세요.",saved:"설정 저장됨",localOnly:"안전한 로컬 연결",thisWebsite:"현재 웹사이트",optIn:"선택 사항",siteHint:"이 도메인에서만 큰 미디어 감지",best:"최고",auto:"자동",localSync:"로컬 동기화",version:"버전",sections:"확장 프로그램 섹션",website:"웹사이트" },
  };
  Object.assign(dictionaries.en, {best:"Best",auto:"Automatic",localSync:"Local sync",version:"Version",sections:"Extension sections",website:"Website"});
  Object.assign(dictionaries.vi, {best:"Tốt nhất",auto:"Tự động",localSync:"Đồng bộ nội bộ",version:"Phiên bản",sections:"Các mục tiện ích",website:"Website"});
  Object.assign(dictionaries.zh, {best:"最佳",auto:"自动",localSync:"本地同步",version:"版本",sections:"扩展程序页面",website:"网站"});
  Object.assign(dictionaries, additional);
  const resolveLanguage = (setting, systemLanguage = 'en') => {
    const code = String(setting === 'auto' ? systemLanguage : setting).toLowerCase().split(/[-_]/)[0];
    return supported.includes(code) ? code : 'en';
  };
  const api = Object.freeze({ supported, dictionaries, resolveLanguage,
    words: (setting, systemLanguage) => dictionaries[resolveLanguage(setting, systemLanguage)] });
  globalThis.VideoBatchPopupI18n = api;
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})();
